/**
 * Ressources réelles des provinces : bassins pétroliers et gaziers, régions minières, greniers
 * agricoles, pôles industriels et électroniques. Données géographiques publiques, citées par zone :
 *  - EIA, International Energy Statistics et fiches pays (pétrole, gaz) ;
 *  - USGS, Mineral Commodity Summaries 2024 et Minerals Yearbook (mines, minerais, charbon) ;
 *  - FAO / FAOSTAT et USDA FAS, Crop Explorer (régions céréalières et agricoles) ;
 *  - SIA / SEMI, OCDE (pôles de fabrication électronique et industrielle).
 *
 * Désignation d'une zone :
 *  - `provinces` : « nation:Nom » où Nom est le nom de la province OU de sa ville principale
 *    (données Natural Earth de data/map/provinces.json) ; un nom inconnu fait échouer les tests ;
 *  - `circle` : [longitude, latitude, rayon km] — une province en fait partie si sa ville ou son
 *    centre est dans le cercle, parmi les `nations` indiquées. Un cercle n'attribue JAMAIS de gisement
 *    à une capitale : seule une désignation explicite le peut (Abou Dabi, cas réel documenté).
 *
 * Richesse : 1 modeste, 2 importante, 3 majeure (rang mondial). Les heuristiques (densité, latitude,
 * aridité, reliefs) sont à part, dans resources.ts, et ne s'appliquent qu'aux provinces sans donnée.
 */
export type Res = 'oil' | 'metals' | 'electronics' | 'food';

export interface ResourceZone {
  id: string;
  /** Région réelle. */
  name: string;
  resource: Res;
  richness: 1 | 2 | 3;
  provinces?: string[];
  circle?: [number, number, number];
  nations?: string[];
  source: string;
}

const EIA = 'EIA International Energy Statistics';
const USGS = 'USGS Mineral Commodity Summaries 2024';
const FAO = 'FAOSTAT / USDA FAS Crop Explorer';
const SEMI = 'SEMI World Fab Watch / OCDE';

export const RESOURCE_ZONES: ResourceZone[] = [
  // ————————————————————————————— Pétrole et gaz —————————————————————————————
  // Algérie : le pétrole et le gaz sont au Sahara, jamais à Alger.
  {
    id: 'dz-hassi-messaoud',
    name: 'Hassi Messaoud',
    resource: 'oil',
    richness: 3,
    provinces: ['dza:Ouargla Nord-Est'],
    source: EIA,
  },
  {
    id: 'dz-hassi-rmel',
    name: "Hassi R'Mel (gaz)",
    resource: 'oil',
    richness: 3,
    provinces: ['dza:Laghouat'],
    source: EIA,
  },
  {
    id: 'dz-in-amenas',
    name: 'In Amenas, bassin d’Illizi',
    resource: 'oil',
    richness: 2,
    provinces: ['dza:Illizi Nord'],
    source: EIA,
  },
  {
    id: 'dz-berkine',
    name: 'Bassin de Berkine',
    resource: 'oil',
    richness: 2,
    provinces: ['dza:Ouargla Sud-Ouest', 'dza:El Oued'],
    source: EIA,
  },
  {
    id: 'dz-reggane',
    name: 'Gaz de Reggane et Timimoun',
    resource: 'oil',
    richness: 1,
    provinces: ['dza:Adrar Nord'],
    source: EIA,
  },
  {
    id: 'ly-sirte',
    name: 'Bassin de Syrte',
    resource: 'oil',
    richness: 3,
    provinces: ['lby:Ajdabiya Sud-Est', 'lby:Ajdabiya Nord-Ouest', 'lby:Syrte'],
    source: EIA,
  },
  {
    id: 'ly-murzuq',
    name: 'Bassin de Murzuq (El Sharara)',
    resource: 'oil',
    richness: 2,
    provinces: ['lby:Wadi al Hayaat', 'lby:Mourzouq Ouest'],
    source: EIA,
  },
  {
    id: 'ly-ghadames',
    name: 'Bassin de Ghadamès',
    resource: 'oil',
    richness: 1,
    provinces: ['lby:Ghadamès'],
    source: EIA,
  },
  {
    id: 'tn-borma',
    name: 'El Borma',
    resource: 'oil',
    richness: 1,
    circle: [9.3, 31.7, 180],
    nations: ['tun'],
    source: EIA,
  },
  {
    id: 'eg-suez',
    name: 'Golfe de Suez',
    resource: 'oil',
    richness: 2,
    circle: [33.0, 28.5, 220],
    nations: ['egy'],
    source: EIA,
  },
  {
    id: 'eg-western',
    name: 'Désert occidental',
    resource: 'oil',
    richness: 1,
    circle: [27.5, 30.0, 300],
    nations: ['egy'],
    source: EIA,
  },
  {
    id: 'sa-ghawar',
    name: 'Ghawar, Province orientale',
    resource: 'oil',
    richness: 3,
    provinces: ['sau:Ach-Charqiya Nord-Ouest', 'sau:Ach-Charqiya Sud-Est', 'sau:Ach-Charqiya Sud'],
    source: EIA,
  },
  {
    id: 'kw-burgan',
    name: 'Burgan et Raudhatain',
    resource: 'oil',
    richness: 3,
    provinces: ['kwt:Al Ahmadi', 'kwt:Al Jahra'],
    source: EIA,
  },
  {
    id: 'qa-north-field',
    name: 'North Field, Ras Laffan',
    resource: 'oil',
    richness: 3,
    provinces: ['qat:Al Khawr'],
    source: EIA,
  },
  {
    id: 'qa-dukhan',
    name: 'Dukhan',
    resource: 'oil',
    richness: 2,
    provinces: ['qat:Al Rayyan'],
    source: EIA,
  },
  {
    id: 'ae-abu-dhabi',
    name: 'Émirat d’Abou Dabi (95 % du pétrole émirien)',
    resource: 'oil',
    richness: 3,
    provinces: ['are:Abou Dabi'],
    source: EIA,
  },
  {
    id: 'bh-awali',
    name: 'Awali',
    resource: 'oil',
    richness: 1,
    provinces: ['bhr:Méridional'],
    source: EIA,
  },
  {
    id: 'om-fahud',
    name: 'Fahud et Oman central',
    resource: 'oil',
    richness: 2,
    provinces: ['omn:Ad Dhahirah', 'omn:Al Wusta', 'omn:Dhofar Nord-Est'],
    source: EIA,
  },
  {
    id: 'iq-rumaila',
    name: 'Rumaila, West Qurna',
    resource: 'oil',
    richness: 3,
    provinces: ['irq:Al-Basra'],
    source: EIA,
  },
  {
    id: 'iq-kirkuk',
    name: 'Kirkouk',
    resource: 'oil',
    richness: 3,
    provinces: ['irq:Kirkouk'],
    source: EIA,
  },
  {
    id: 'iq-south',
    name: 'Maysan, Dhi Qar',
    resource: 'oil',
    richness: 2,
    provinces: ['irq:Maysan', 'irq:Dhi Qar'],
    source: EIA,
  },
  {
    id: 'iq-north',
    name: 'Kurdistan irakien, Baiji',
    resource: 'oil',
    richness: 1,
    provinces: ['irq:Erbil', 'irq:Salah ad-Din'],
    source: EIA,
  },
  {
    id: 'ir-khuzestan',
    name: 'Khouzistan (Ahvaz, Marun)',
    resource: 'oil',
    richness: 3,
    provinces: ['irn:Khouzistan'],
    source: EIA,
  },
  {
    id: 'ir-south-pars',
    name: 'South Pars (gaz), Bouchehr',
    resource: 'oil',
    richness: 3,
    provinces: ['irn:Bouchehr'],
    source: EIA,
  },
  {
    id: 'ir-zagros',
    name: 'Piémont du Zagros',
    resource: 'oil',
    richness: 2,
    provinces: ['irn:Kohguilouyeh-et-Bouyer-Ahmad', 'irn:Ilam'],
    source: EIA,
  },
  {
    id: 'sy-deir',
    name: 'Deir ez-Zor',
    resource: 'oil',
    richness: 1,
    circle: [40.5, 35.2, 200],
    nations: ['syr'],
    source: EIA,
  },
  {
    id: 'ye-marib',
    name: 'Marib, Hadramaout',
    resource: 'oil',
    richness: 1,
    circle: [47.5, 15.6, 300],
    nations: ['yem'],
    source: EIA,
  },
  {
    id: 'ru-west-siberia',
    name: 'Sibérie occidentale (Samotlor, Sourgout)',
    resource: 'oil',
    richness: 3,
    provinces: [
      'rus:Khantys-Mansis Ouest',
      'rus:Khantys-Mansis Est',
      'rus:Khantys-Mansis Sud-Ouest',
    ],
    source: EIA,
  },
  {
    id: 'ru-yamal',
    name: 'Iamal, Ourengoï (gaz)',
    resource: 'oil',
    richness: 3,
    provinces: ['rus:Iamalie Nord', 'rus:Iamalie Sud-Ouest', 'rus:Iamalie Sud-Est'],
    source: EIA,
  },
  {
    id: 'ru-tomsk',
    name: 'Vassiougan (Tomsk)',
    resource: 'oil',
    richness: 2,
    provinces: ['rus:Tomsk Ouest'],
    source: EIA,
  },
  {
    id: 'ru-volga-ural',
    name: 'Volga-Oural (Romachkino)',
    resource: 'oil',
    richness: 2,
    provinces: [
      'rus:Tatarstan',
      'rus:Bachkirie Nord',
      'rus:Samara',
      'rus:Oudmourtie',
      'rus:Perm Sud',
    ],
    source: EIA,
  },
  {
    id: 'ru-orenburg',
    name: 'Gaz d’Orenbourg',
    resource: 'oil',
    richness: 2,
    provinces: ['rus:Orenbourg Ouest'],
    source: EIA,
  },
  {
    id: 'ru-timan-pechora',
    name: 'Timan-Petchora',
    resource: 'oil',
    richness: 1,
    provinces: ['rus:République des Komis Nord-Ouest', 'rus:Nénétsie Est', 'rus:Nénétsie Ouest'],
    source: EIA,
  },
  {
    id: 'ru-sakhalin',
    name: 'Sakhaline I et II',
    resource: 'oil',
    richness: 2,
    provinces: ['rus:Sakhaline'],
    source: EIA,
  },
  {
    id: 'ru-east-siberia',
    name: 'Sibérie orientale (Vankor, Tchaïanda, Kovykta)',
    resource: 'oil',
    richness: 1,
    provinces: ['rus:Krasnoïarsk Nord-Ouest', 'rus:Irkoutsk Nord', 'rus:Astrakhan'],
    source: EIA,
  },
  {
    id: 'kz-tengiz',
    name: 'Tengiz et Kachagan',
    resource: 'oil',
    richness: 3,
    provinces: ['kaz:Atyraou'],
    source: EIA,
  },
  {
    id: 'kz-karachaganak',
    name: 'Karatchaganak',
    resource: 'oil',
    richness: 2,
    provinces: ['kaz:Kazakhstan-Occidental Nord-Est'],
    source: EIA,
  },
  {
    id: 'kz-mangystau',
    name: 'Manguistaou (Ouzen)',
    resource: 'oil',
    richness: 2,
    provinces: ['kaz:Manguistaou Nord', 'kaz:Manguistaou Sud'],
    source: EIA,
  },
  {
    id: 'kz-aktobe',
    name: 'Aktioubé, Kyzylorda',
    resource: 'oil',
    richness: 1,
    provinces: ['kaz:Aqtöbe Ouest', 'kaz:Kyzylorda Est'],
    source: EIA,
  },
  {
    id: 'az-absheron',
    name: 'Azeri-Chirag-Guneshli (Bakou)',
    resource: 'oil',
    richness: 2,
    circle: [49.5, 40.3, 150],
    nations: ['aze'],
    source: EIA,
  },
  {
    id: 'tm-galkynysh',
    name: 'Galkynych (gaz)',
    resource: 'oil',
    richness: 3,
    circle: [62.3, 37.4, 250],
    nations: ['tkm'],
    source: EIA,
  },
  {
    id: 'tm-balkan',
    name: 'Balkan (Caspienne)',
    resource: 'oil',
    richness: 2,
    circle: [53.8, 39.5, 250],
    nations: ['tkm'],
    source: EIA,
  },
  {
    id: 'uz-bukhara',
    name: 'Gaz de Boukhara-Khiva',
    resource: 'oil',
    richness: 1,
    circle: [64.4, 39.0, 220],
    nations: ['uzb'],
    source: EIA,
  },
  {
    id: 'us-permian',
    name: 'Bassin permien',
    resource: 'oil',
    richness: 3,
    provinces: ['usa:Texas Ouest', 'usa:Nouveau-Mexique Sud'],
    source: EIA,
  },
  {
    id: 'us-prudhoe',
    name: 'Prudhoe Bay',
    resource: 'oil',
    richness: 3,
    provinces: ['usa:Alaska Nord'],
    source: EIA,
  },
  {
    id: 'us-bakken',
    name: 'Bakken',
    resource: 'oil',
    richness: 2,
    provinces: ['usa:Dakota du Nord Ouest'],
    source: EIA,
  },
  {
    id: 'us-eagle-ford',
    name: 'Eagle Ford',
    resource: 'oil',
    richness: 2,
    provinces: ['usa:Texas Sud'],
    source: EIA,
  },
  {
    id: 'us-gulf',
    name: 'Golfe du Mexique (Louisiane)',
    resource: 'oil',
    richness: 2,
    provinces: ['usa:Louisiane Sud-Est'],
    source: EIA,
  },
  {
    id: 'us-anadarko',
    name: 'Anadarko (Oklahoma)',
    resource: 'oil',
    richness: 2,
    provinces: ['usa:Oklahoma Ouest'],
    source: EIA,
  },
  {
    id: 'us-marcellus',
    name: 'Marcellus (gaz)',
    resource: 'oil',
    richness: 2,
    provinces: ['usa:Pennsylvanie Ouest', 'usa:Virginie-Occidentale'],
    source: EIA,
  },
  {
    id: 'us-rockies',
    name: 'Bassins des Rocheuses (DJ, Powder River, Uinta)',
    resource: 'oil',
    richness: 1,
    provinces: ['usa:Colorado Est', 'usa:Wyoming Ouest', 'usa:Utah Nord', 'usa:Montana Est'],
    source: EIA,
  },
  {
    id: 'us-misc',
    name: 'Haynesville, Kern County, Hugoton',
    resource: 'oil',
    richness: 1,
    provinces: [
      'usa:Louisiane Nord-Ouest',
      'usa:Californie Sud',
      'usa:Kansas Ouest',
      'usa:Texas Nord-Ouest',
    ],
    source: EIA,
  },
  {
    id: 'ca-oil-sands',
    name: 'Sables bitumineux de l’Athabasca',
    resource: 'oil',
    richness: 3,
    provinces: ['can:Alberta Nord'],
    source: EIA,
  },
  {
    id: 'ca-alberta',
    name: 'Bassin sédimentaire de l’Ouest canadien',
    resource: 'oil',
    richness: 2,
    provinces: ['can:Alberta Ouest', 'can:Colombie-Britannique Nord-Est'],
    source: EIA,
  },
  {
    id: 'ca-hibernia',
    name: 'Hibernia (Grands Bancs)',
    resource: 'oil',
    richness: 1,
    provinces: ['can:Terre-Neuve-et-Labrador Sud-Est'],
    source: EIA,
  },
  {
    id: 'mx-cantarell',
    name: 'Cantarell, Ku-Maloob-Zaap',
    resource: 'oil',
    richness: 3,
    provinces: ['mex:Campeche'],
    source: EIA,
  },
  {
    id: 'mx-tabasco',
    name: 'Tabasco, Veracruz',
    resource: 'oil',
    richness: 2,
    provinces: ['mex:Tabasco', 'mex:Veracruz', 'mex:Tamaulipas'],
    source: EIA,
  },
  {
    id: 've-maracaibo',
    name: 'Lac de Maracaibo',
    resource: 'oil',
    richness: 3,
    provinces: ['ven:Zulia'],
    source: EIA,
  },
  {
    id: 've-orinoco',
    name: 'Ceinture de l’Orénoque',
    resource: 'oil',
    richness: 3,
    provinces: ['ven:Monagas', 'ven:Anzoátegui'],
    source: EIA,
  },
  {
    id: 've-llanos',
    name: 'Llanos (Barinas, Guárico)',
    resource: 'oil',
    richness: 1,
    provinces: ['ven:Barinas', 'ven:Guárico'],
    source: EIA,
  },
  {
    id: 'co-llanos',
    name: 'Llanos (Meta, Casanare)',
    resource: 'oil',
    richness: 2,
    circle: [-72.0, 4.5, 250],
    nations: ['col'],
    source: EIA,
  },
  {
    id: 'ec-oriente',
    name: 'Oriente équatorien',
    resource: 'oil',
    richness: 2,
    circle: [-76.6, -0.6, 200],
    nations: ['ecu'],
    source: EIA,
  },
  {
    id: 'pe-camisea',
    name: 'Camisea (gaz), Loreto',
    resource: 'oil',
    richness: 1,
    provinces: ['per:Cuzco', 'per:Loreto Nord-Ouest'],
    source: EIA,
  },
  {
    id: 'bo-tarija',
    name: 'Gaz de Tarija',
    resource: 'oil',
    richness: 2,
    circle: [-63.6, -21.4, 200],
    nations: ['bol'],
    source: EIA,
  },
  {
    id: 'tt-trinidad',
    name: 'Trinité (gaz)',
    resource: 'oil',
    richness: 2,
    circle: [-61.3, 10.4, 100],
    nations: ['tto'],
    source: EIA,
  },
  {
    id: 'br-campos',
    name: 'Bassins de Campos et Santos (pré-sel)',
    resource: 'oil',
    richness: 3,
    provinces: ['bra:Rio de Janeiro Nord-Est'],
    source: EIA,
  },
  {
    id: 'br-espirito-santo',
    name: 'Bassin d’Espírito Santo',
    resource: 'oil',
    richness: 2,
    provinces: ['bra:Espírito Santo'],
    source: EIA,
  },
  {
    id: 'br-onshore',
    name: 'Urucu, Sergipe, Recôncavo',
    resource: 'oil',
    richness: 1,
    provinces: ['bra:Amazonas Nord', 'bra:Sergipe'],
    source: EIA,
  },
  {
    id: 'ar-vaca-muerta',
    name: 'Vaca Muerta',
    resource: 'oil',
    richness: 3,
    provinces: ['arg:Neuquén'],
    source: EIA,
  },
  {
    id: 'ar-san-jorge',
    name: 'Golfe San Jorge',
    resource: 'oil',
    richness: 2,
    provinces: ['arg:Chubut Ouest', 'arg:Santa Cruz Nord'],
    source: EIA,
  },
  {
    id: 'ar-cuyo',
    name: 'Bassins de Cuyo et du Nord-Ouest',
    resource: 'oil',
    richness: 1,
    provinces: ['arg:Mendoza Sud', 'arg:Salta Nord-Est'],
    source: EIA,
  },
  {
    id: 'ng-niger-delta',
    name: 'Delta du Niger',
    resource: 'oil',
    richness: 3,
    provinces: ['nga:Rivers', 'nga:Delta'],
    source: EIA,
  },
  {
    id: 'ng-delta-fringe',
    name: 'Bordure du delta du Niger',
    resource: 'oil',
    richness: 1,
    provinces: ['nga:Cross River', 'nga:Abia', 'nga:Edo'],
    source: EIA,
  },
  {
    id: 'ao-offshore',
    name: 'Cabinda et bassin du Bas-Congo',
    resource: 'oil',
    richness: 3,
    circle: [12.6, -6.0, 300],
    nations: ['ago'],
    source: EIA,
  },
  {
    id: 'ga-port-gentil',
    name: 'Port-Gentil',
    resource: 'oil',
    richness: 2,
    circle: [9.0, -1.0, 200],
    nations: ['gab'],
    source: EIA,
  },
  {
    id: 'cg-pointe-noire',
    name: 'Pointe-Noire',
    resource: 'oil',
    richness: 2,
    circle: [11.9, -4.8, 150],
    nations: ['cog'],
    source: EIA,
  },
  {
    id: 'gq-rio-muni',
    name: 'Zafiro, Rio Muni',
    resource: 'oil',
    richness: 2,
    circle: [9.8, 1.7, 200],
    nations: ['gnq'],
    source: EIA,
  },
  {
    id: 'cm-rio-del-rey',
    name: 'Rio del Rey',
    resource: 'oil',
    richness: 1,
    circle: [9.0, 4.6, 120],
    nations: ['cmr'],
    source: EIA,
  },
  {
    id: 'td-doba',
    name: 'Doba',
    resource: 'oil',
    richness: 1,
    circle: [16.8, 8.6, 200],
    nations: ['tcd'],
    source: EIA,
  },
  {
    id: 'ss-unity',
    name: 'Unité, Haut-Nil',
    resource: 'oil',
    richness: 2,
    circle: [31.0, 9.5, 300],
    nations: ['ssd'],
    source: EIA,
  },
  {
    id: 'sd-heglig',
    name: 'Kordofan occidental',
    resource: 'oil',
    richness: 1,
    circle: [28.5, 10.8, 250],
    nations: ['sdn'],
    source: EIA,
  },
  {
    id: 'gb-north-sea',
    name: 'Mer du Nord (Aberdeen)',
    resource: 'oil',
    richness: 2,
    provinces: ['gbr:Highlands et îles'],
    source: EIA,
  },
  {
    id: 'no-north-sea',
    name: 'Mer du Nord (Ekofisk, Troll, Johan Sverdrup)',
    resource: 'oil',
    richness: 3,
    provinces: ['nor:Rogaland', 'nor:Hordaland'],
    source: EIA,
  },
  {
    id: 'no-norwegian-sea',
    name: 'Mer de Norvège et de Barents',
    resource: 'oil',
    richness: 2,
    provinces: ['nor:Møre og Romsdal', 'nor:Nordland', 'nor:Finnmark'],
    source: EIA,
  },
  {
    id: 'nl-groningen',
    name: 'Gaz de Groningue',
    resource: 'oil',
    richness: 1,
    provinces: ['nld:Groningue'],
    source: EIA,
  },
  {
    id: 'dk-esbjerg',
    name: 'Mer du Nord danoise',
    resource: 'oil',
    richness: 1,
    circle: [8.5, 55.5, 120],
    nations: ['dnk'],
    source: EIA,
  },
  {
    id: 'ro-ploiesti',
    name: 'Ploiești',
    resource: 'oil',
    richness: 1,
    circle: [26.0, 44.9, 100],
    nations: ['rou'],
    source: EIA,
  },
  {
    id: 'ua-poltava',
    name: 'Gaz du Dniepr-Donets',
    resource: 'oil',
    richness: 1,
    provinces: ['ukr:Poltava', 'ukr:Kharkiv'],
    source: EIA,
  },
  {
    id: 'tr-batman',
    name: 'Batman',
    resource: 'oil',
    richness: 1,
    circle: [41.1, 37.9, 100],
    nations: ['tur'],
    source: EIA,
  },
  {
    id: 'pk-sui',
    name: 'Gaz de Sui',
    resource: 'oil',
    richness: 1,
    circle: [69.2, 28.6, 200],
    nations: ['pak'],
    source: EIA,
  },
  {
    id: 'cn-daqing',
    name: 'Daqing',
    resource: 'oil',
    richness: 2,
    provinces: ['chn:Heilongjiang Sud-Ouest'],
    source: EIA,
  },
  {
    id: 'cn-shengli',
    name: 'Shengli',
    resource: 'oil',
    richness: 2,
    provinces: ['chn:Shandong Nord'],
    source: EIA,
  },
  {
    id: 'cn-xinjiang',
    name: 'Karamay, Tarim',
    resource: 'oil',
    richness: 2,
    provinces: ['chn:Xinjiang Nord', 'chn:Xinjiang Nord-Ouest'],
    source: EIA,
  },
  {
    id: 'cn-ordos',
    name: 'Changqing (bassin de l’Ordos)',
    resource: 'oil',
    richness: 2,
    provinces: ['chn:Shaanxi Nord'],
    source: EIA,
  },
  {
    id: 'cn-misc',
    name: 'Qaidam, Liaohe, Sichuan (gaz)',
    resource: 'oil',
    richness: 1,
    provinces: ['chn:Qinghai Nord-Ouest', 'chn:Liaoning Ouest', 'chn:Sichuan Est'],
    source: EIA,
  },
  {
    id: 'in-onshore',
    name: 'Assam, Barmer, Cambay',
    resource: 'oil',
    richness: 1,
    provinces: ['ind:Assam Nord-Est', 'ind:Rajasthan Ouest', 'ind:Gujarat Ouest'],
    source: EIA,
  },
  {
    id: 'id-riau',
    name: 'Minas, Duri',
    resource: 'oil',
    richness: 2,
    provinces: ['idn:Riau'],
    source: EIA,
  },
  {
    id: 'id-mahakam',
    name: 'Delta de la Mahakam',
    resource: 'oil',
    richness: 2,
    provinces: ['idn:Kalimantan oriental Sud'],
    source: EIA,
  },
  {
    id: 'id-misc',
    name: 'Sumatra du Sud, Tangguh, Arun',
    resource: 'oil',
    richness: 1,
    provinces: ['idn:Sumatra du Sud Est', 'idn:Papouasie occidentale', 'idn:Aceh'],
    source: EIA,
  },
  {
    id: 'my-offshore',
    name: 'Sarawak, Sabah, Terengganu',
    resource: 'oil',
    richness: 2,
    circle: [113.0, 3.2, 250],
    nations: ['mys'],
    source: EIA,
  },
  {
    id: 'my-terengganu',
    name: 'Terengganu',
    resource: 'oil',
    richness: 1,
    circle: [103.1, 5.3, 100],
    nations: ['mys'],
    source: EIA,
  },
  {
    id: 'bn-belait',
    name: 'Seria (Belait)',
    resource: 'oil',
    richness: 3,
    provinces: ['brn:Belait'],
    source: EIA,
  },
  {
    id: 'au-north-west-shelf',
    name: 'North West Shelf (gaz)',
    resource: 'oil',
    richness: 3,
    provinces: ['aus:Australie-Occidentale Nord'],
    source: EIA,
  },
  {
    id: 'au-misc',
    name: 'Ichthys (Darwin), bassin de Surat',
    resource: 'oil',
    richness: 1,
    provinces: ['aus:Territoire du Nord Nord', 'aus:Queensland Sud'],
    source: EIA,
  },
  {
    id: 'vn-bach-ho',
    name: 'Bach Ho (Vung Tau)',
    resource: 'oil',
    richness: 1,
    circle: [107.1, 10.4, 100],
    nations: ['vnm'],
    source: EIA,
  },

  // ————————————————————————————— Mines et minerais —————————————————————————————
  {
    id: 'au-pilbara',
    name: 'Pilbara (fer)',
    resource: 'metals',
    richness: 3,
    provinces: ['aus:Australie-Occidentale Nord'],
    source: USGS,
  },
  {
    id: 'au-goldfields',
    name: 'Goldfields (or, nickel)',
    resource: 'metals',
    richness: 3,
    provinces: ['aus:Australie-Occidentale Est'],
    source: USGS,
  },
  {
    id: 'au-mount-isa',
    name: 'Mount Isa',
    resource: 'metals',
    richness: 3,
    provinces: ['aus:Queensland Nord-Ouest'],
    source: USGS,
  },
  {
    id: 'au-olympic-dam',
    name: 'Olympic Dam',
    resource: 'metals',
    richness: 3,
    circle: [136.9, -30.4, 200],
    nations: ['aus'],
    source: USGS,
  },
  {
    id: 'au-broken-hill',
    name: 'Broken Hill',
    resource: 'metals',
    richness: 2,
    provinces: ['aus:Nouvelle-Galles du Sud Ouest'],
    source: USGS,
  },
  {
    id: 'au-bowen',
    name: 'Bassin de Bowen (charbon)',
    resource: 'metals',
    richness: 2,
    provinces: ['aus:Queensland Est'],
    source: USGS,
  },
  {
    id: 'au-misc-metals',
    name: 'Mid West, Tasmanie',
    resource: 'metals',
    richness: 1,
    provinces: ['aus:Australie-Occidentale Centre', 'aus:Tasmanie'],
    source: USGS,
  },
  {
    id: 'cl-escondida',
    name: 'Escondida, Chuquicamata',
    resource: 'metals',
    richness: 3,
    provinces: ['chl:Antofagasta'],
    source: USGS,
  },
  {
    id: 'cl-norte',
    name: 'Collahuasi, Candelaria, El Teniente',
    resource: 'metals',
    richness: 2,
    provinces: ['chl:Tarapacá', 'chl:Atacama', "chl:O'Higgins"],
    source: USGS,
  },
  {
    id: 'cl-coquimbo',
    name: 'Los Pelambres',
    resource: 'metals',
    richness: 1,
    provinces: ['chl:Coquimbo'],
    source: USGS,
  },
  {
    id: 'pe-andes',
    name: 'Cerro Verde, Antamina, Las Bambas, Yanacocha',
    resource: 'metals',
    richness: 2,
    provinces: [
      'per:Arequipa',
      'per:Moquegua',
      'per:Ancash',
      'per:Apurímac',
      'per:Cajamarca',
      'per:Pasco',
    ],
    source: USGS,
  },
  {
    id: 'pe-misc',
    name: 'Toquepala, Junín, Puno',
    resource: 'metals',
    richness: 1,
    provinces: ['per:Tacna', 'per:Junín', 'per:Puno'],
    source: USGS,
  },
  {
    id: 'bo-potosi',
    name: 'Potosí, Uyuni (argent, étain, lithium)',
    resource: 'metals',
    richness: 3,
    circle: [-66.5, -20.3, 280],
    nations: ['bol'],
    source: USGS,
  },
  {
    id: 'cd-katanga',
    name: 'Arc cuprifère du Katanga',
    resource: 'metals',
    richness: 3,
    provinces: ['cod:Katanga Sud-Est'],
    source: USGS,
  },
  {
    id: 'cd-kolwezi',
    name: 'Kolwezi (cobalt)',
    resource: 'metals',
    richness: 3,
    circle: [25.5, -10.7, 150],
    nations: ['cod'],
    source: USGS,
  },
  {
    id: 'cd-mbuji-mayi',
    name: 'Mbuji-Mayi (diamants)',
    resource: 'metals',
    richness: 2,
    provinces: ['cod:Kasaï-Oriental Sud'],
    source: USGS,
  },
  {
    id: 'cd-kivu',
    name: 'Kivu (coltan, or), Kibali',
    resource: 'metals',
    richness: 1,
    provinces: ['cod:Sud-Kivu', 'cod:Nord-Kivu', 'cod:Orientale Est'],
    source: USGS,
  },
  {
    id: 'zm-copperbelt',
    name: 'Copperbelt zambien',
    resource: 'metals',
    richness: 3,
    provinces: ['zmb:Copperbelt', 'zmb:Nord-Occidentale'],
    source: USGS,
  },
  {
    id: 'za-bushveld',
    name: 'Complexe du Bushveld (platine)',
    resource: 'metals',
    richness: 3,
    provinces: ['zaf:Nord-Ouest', 'zaf:Limpopo Ouest'],
    source: USGS,
  },
  {
    id: 'za-witwatersrand',
    name: 'Or du Witwatersrand (Welkom)',
    resource: 'metals',
    richness: 2,
    provinces: ['zaf:État libre Nord-Est'],
    source: USGS,
  },
  {
    id: 'za-northern-cape',
    name: 'Sishen (fer), Kimberley (diamants)',
    resource: 'metals',
    richness: 2,
    provinces: ['zaf:Cap-Nord Nord', 'zaf:Cap-Nord Sud-Est'],
    source: USGS,
  },
  {
    id: 'za-mpumalanga',
    name: 'Charbon du Mpumalanga',
    resource: 'metals',
    richness: 2,
    provinces: ['zaf:Mpumalanga'],
    source: USGS,
  },
  {
    id: 'bw-diamonds',
    name: 'Jwaneng, Orapa (diamants)',
    resource: 'metals',
    richness: 3,
    circle: [24.9, -23.0, 250],
    nations: ['bwa'],
    source: USGS,
  },
  {
    id: 'na-erongo',
    name: 'Erongo (uranium), Namib (diamants)',
    resource: 'metals',
    richness: 2,
    circle: [15.2, -22.5, 300],
    nations: ['nam'],
    source: USGS,
  },
  {
    id: 'zw-great-dyke',
    name: 'Great Dyke',
    resource: 'metals',
    richness: 1,
    circle: [30.0, -18.5, 200],
    nations: ['zwe'],
    source: USGS,
  },
  {
    id: 'gn-boke',
    name: 'Boké (bauxite)',
    resource: 'metals',
    richness: 3,
    circle: [-14.3, 10.9, 180],
    nations: ['gin'],
    source: USGS,
  },
  {
    id: 'gn-simandou',
    name: 'Simandou (fer)',
    resource: 'metals',
    richness: 2,
    circle: [-8.9, 8.6, 150],
    nations: ['gin'],
    source: USGS,
  },
  {
    id: 'mr-zouerate',
    name: 'Zouérate (fer)',
    resource: 'metals',
    richness: 2,
    circle: [-12.5, 22.7, 250],
    nations: ['mrt'],
    source: USGS,
  },
  {
    id: 'ma-khouribga',
    name: 'Khouribga, Benguérir (phosphates)',
    resource: 'metals',
    richness: 3,
    circle: [-7.3, 32.6, 100],
    nations: ['mar'],
    source: USGS,
  },
  {
    id: 'eh-boucraa',
    name: 'Boucraa (phosphates)',
    resource: 'metals',
    richness: 2,
    circle: [-12.9, 26.3, 150],
    nations: ['mar', 'esh', 'sah'],
    source: USGS,
  },
  {
    id: 'dz-gara-djebilet',
    name: 'Gara Djebilet (fer)',
    resource: 'metals',
    richness: 2,
    circle: [-7.25, 26.75, 150],
    nations: ['dza'],
    source: USGS,
  },
  {
    id: 'dz-tebessa',
    name: 'Ouenza (fer), Djebel Onk (phosphates)',
    resource: 'metals',
    richness: 2,
    provinces: ['dza:Tébessa'],
    source: USGS,
  },
  {
    id: 'dz-hoggar',
    name: 'Or du Hoggar (Amesmessa)',
    resource: 'metals',
    richness: 1,
    provinces: ['dza:Tamanrasset Sud-Ouest'],
    source: USGS,
  },
  {
    id: 'tn-gafsa',
    name: 'Gafsa (phosphates)',
    resource: 'metals',
    richness: 2,
    circle: [8.8, 34.4, 80],
    nations: ['tun'],
    source: USGS,
  },
  {
    id: 'gh-ashanti',
    name: 'Ashanti (or)',
    resource: 'metals',
    richness: 2,
    circle: [-1.8, 6.2, 120],
    nations: ['gha'],
    source: USGS,
  },
  {
    id: 'ml-kayes',
    name: 'Sadiola, Loulo (or)',
    resource: 'metals',
    richness: 1,
    circle: [-11.2, 13.5, 200],
    nations: ['mli'],
    source: USGS,
  },
  {
    id: 'ne-arlit',
    name: 'Arlit (uranium)',
    resource: 'metals',
    richness: 2,
    circle: [7.4, 18.7, 250],
    nations: ['ner'],
    source: USGS,
  },
  {
    id: 'tz-geita',
    name: 'Geita (or)',
    resource: 'metals',
    richness: 1,
    circle: [32.2, -2.9, 150],
    nations: ['tza'],
    source: USGS,
  },
  {
    id: 'ga-moanda',
    name: 'Moanda (manganèse)',
    resource: 'metals',
    richness: 2,
    circle: [13.2, -1.55, 120],
    nations: ['gab'],
    source: USGS,
  },
  {
    id: 'mz-moatize',
    name: 'Moatize (charbon)',
    resource: 'metals',
    richness: 1,
    circle: [33.6, -16.1, 150],
    nations: ['moz'],
    source: USGS,
  },
  {
    id: 'mg-ambatovy',
    name: 'Ambatovy (nickel)',
    resource: 'metals',
    richness: 1,
    circle: [48.3, -18.8, 100],
    nations: ['mdg'],
    source: USGS,
  },
  {
    id: 'ru-norilsk',
    name: 'Norilsk (nickel, palladium)',
    resource: 'metals',
    richness: 3,
    provinces: ['rus:Krasnoïarsk Nord-Ouest'],
    source: USGS,
  },
  {
    id: 'ru-kuzbass',
    name: 'Kouzbass (charbon)',
    resource: 'metals',
    richness: 3,
    provinces: ['rus:Kemerovo'],
    source: USGS,
  },
  {
    id: 'ru-mirny',
    name: 'Mirny (diamants)',
    resource: 'metals',
    richness: 3,
    provinces: ['rus:République Sakha Sud-Ouest'],
    source: USGS,
  },
  {
    id: 'ru-urals',
    name: 'Oural (fer, cuivre, aciéries)',
    resource: 'metals',
    richness: 2,
    provinces: [
      'rus:Sverdlovsk Nord',
      'rus:Sverdlovsk Sud',
      'rus:Tcheliabinsk',
      'rus:Orenbourg Est',
    ],
    source: USGS,
  },
  {
    id: 'ru-kma',
    name: 'Anomalie magnétique de Koursk (fer)',
    resource: 'metals',
    richness: 2,
    provinces: ['rus:Belgorod', 'rus:Koursk'],
    source: USGS,
  },
  {
    id: 'ru-kola',
    name: 'Péninsule de Kola (apatite, nickel)',
    resource: 'metals',
    richness: 2,
    provinces: ['rus:Mourmansk Ouest', 'rus:Mourmansk Est'],
    source: USGS,
  },
  {
    id: 'ru-gold',
    name: 'Or de Magadan, Bodaïbo, Tchoukotka',
    resource: 'metals',
    richness: 2,
    provinces: [
      'rus:Magadan Sud-Ouest',
      'rus:Magadan Nord',
      'rus:Irkoutsk Est',
      'rus:Tchoukotka Ouest',
    ],
    source: USGS,
  },
  {
    id: 'ru-misc',
    name: 'Krasnokamensk (uranium), Berezniki (potasse), Vorkouta, Kostomoukcha',
    resource: 'metals',
    richness: 1,
    provinces: [
      'rus:Transbaïkalie Sud-Est',
      'rus:Perm Nord',
      'rus:République des Komis Nord-Est',
      'rus:Carélie Nord',
      'rus:Khakassie',
      'rus:Amour Nord-Ouest',
    ],
    source: USGS,
  },
  {
    id: 'kz-karaganda',
    name: 'Karaganda (charbon, acier), Djezkazgan (cuivre)',
    resource: 'metals',
    richness: 2,
    provinces: [
      'kaz:Karaganda Est',
      'kaz:Karaganda Ouest',
      'kaz:Kazakhstan-Oriental Est',
      'kaz:Pavlodar',
    ],
    source: USGS,
  },
  {
    id: 'kz-uranium',
    name: 'Uranium du Sud-Kazakhstan, fer de Roudny',
    resource: 'metals',
    richness: 2,
    provinces: ['kaz:Oblys du Turkestan', 'kaz:Kostanaï Nord'],
    source: USGS,
  },
  {
    id: 'mn-oyu-tolgoi',
    name: 'Oyu Tolgoï, Tavan Tolgoï',
    resource: 'metals',
    richness: 3,
    circle: [106.5, 43.3, 280],
    nations: ['mng'],
    source: USGS,
  },
  {
    id: 'mn-erdenet',
    name: 'Erdenet (cuivre)',
    resource: 'metals',
    richness: 2,
    circle: [104.1, 49.0, 120],
    nations: ['mng'],
    source: USGS,
  },
  {
    id: 'cn-bayan-obo',
    name: 'Bayan Obo (terres rares)',
    resource: 'metals',
    richness: 3,
    provinces: ['chn:Mongolie-Intérieure Sud'],
    source: USGS,
  },
  {
    id: 'cn-coal',
    name: 'Charbon du Shanxi et de l’Ordos',
    resource: 'metals',
    richness: 2,
    provinces: ['chn:Shanxi Nord', 'chn:Shanxi Centre', 'chn:Mongolie-Intérieure Sud-Ouest'],
    source: USGS,
  },
  {
    id: 'cn-iron',
    name: 'Fer de Tangshan, Anshan-Benxi, Panzhihua',
    resource: 'metals',
    richness: 2,
    provinces: ['chn:Hebei Nord-Est', 'chn:Liaoning Est', 'chn:Sichuan Sud'],
    source: USGS,
  },
  {
    id: 'cn-south',
    name: 'Ganzhou (terres rares, tungstène), Dexing (cuivre), Jinchuan (nickel)',
    resource: 'metals',
    richness: 2,
    provinces: ['chn:Jiangxi Sud', 'chn:Jiangxi Nord-Est', 'chn:Gansu Est'],
    source: USGS,
  },
  {
    id: 'cn-misc-metals',
    name: 'Gejiu (étain), Hechi, Shizhuyuan',
    resource: 'metals',
    richness: 1,
    provinces: ['chn:Yunnan Sud-Est', 'chn:Guangxi Nord', 'chn:Hunan Sud-Est', 'chn:Anhui Sud-Est'],
    source: USGS,
  },
  {
    id: 'in-jharkhand',
    name: 'Charbon de Dhanbad, fer de Jamshedpur',
    resource: 'metals',
    richness: 2,
    provinces: ['ind:Jharkhand Nord-Est', 'ind:Jharkhand Sud-Ouest', 'ind:Chhattisgarh Sud'],
    source: USGS,
  },
  {
    id: 'in-odisha',
    name: 'Odisha (fer, bauxite)',
    resource: 'metals',
    richness: 3,
    provinces: ['ind:Odisha Nord-Ouest'],
    source: USGS,
  },
  {
    id: 'in-misc',
    name: 'Bellary, Goa (fer), Zawar (zinc)',
    resource: 'metals',
    richness: 1,
    provinces: ['ind:Karnataka Centre', 'ind:Goa'],
    source: USGS,
  },
  {
    id: 'in-zawar',
    name: 'Zawar (zinc)',
    resource: 'metals',
    richness: 1,
    circle: [73.7, 24.4, 100],
    nations: ['ind'],
    source: USGS,
  },
  {
    id: 'br-carajas',
    name: 'Carajás (fer)',
    resource: 'metals',
    richness: 3,
    provinces: ['bra:Pará Sud-Est'],
    source: USGS,
  },
  {
    id: 'br-quadrilatero',
    name: 'Quadrilatère ferrifère (Minas Gerais)',
    resource: 'metals',
    richness: 3,
    provinces: ['bra:Minas Gerais Sud'],
    source: USGS,
  },
  {
    id: 'br-misc',
    name: 'Vale do Aço, Trombetas (bauxite), Niquelândia',
    resource: 'metals',
    richness: 1,
    provinces: ['bra:Minas Gerais Est', 'bra:Pará Nord', 'bra:Goiás Nord'],
    source: USGS,
  },
  {
    id: 'ca-sudbury',
    name: 'Sudbury (nickel), Timmins (or)',
    resource: 'metals',
    richness: 3,
    provinces: ['can:Ontario Sud-Est', 'can:Ontario Nord-Est'],
    source: USGS,
  },
  {
    id: 'ca-athabasca',
    name: 'Bassin d’Athabasca (uranium)',
    resource: 'metals',
    richness: 3,
    provinces: ['can:Saskatchewan Nord'],
    source: USGS,
  },
  {
    id: 'ca-labrador',
    name: 'Fosse du Labrador (fer)',
    resource: 'metals',
    richness: 2,
    provinces: ['can:Terre-Neuve-et-Labrador Nord-Ouest'],
    source: USGS,
  },
  {
    id: 'ca-north',
    name: 'Yellowknife (diamants), Thompson (nickel), Klondike',
    resource: 'metals',
    richness: 1,
    provinces: [
      'can:Territoires du Nord-Ouest Sud-Est',
      'can:Manitoba Nord',
      'can:Yukon Sud-Ouest',
    ],
    source: USGS,
  },
  {
    id: 'us-copper',
    name: 'Morenci, Bingham Canyon (cuivre)',
    resource: 'metals',
    richness: 3,
    provinces: ['usa:Arizona Sud-Est'],
    source: USGS,
  },
  {
    id: 'us-mesabi',
    name: 'Mesabi Range (fer)',
    resource: 'metals',
    richness: 3,
    provinces: ['usa:Minnesota Nord'],
    source: USGS,
  },
  {
    id: 'us-carlin',
    name: 'Carlin Trend (or)',
    resource: 'metals',
    richness: 2,
    provinces: ['usa:Nevada Nord-Ouest'],
    source: USGS,
  },
  {
    id: 'us-coal',
    name: 'Powder River (charbon), Red Dog (zinc)',
    resource: 'metals',
    richness: 2,
    provinces: ['usa:Wyoming Est', 'usa:Alaska Nord-Ouest'],
    source: USGS,
  },
  {
    id: 'us-misc-metals',
    name: 'Butte, Coeur d’Alene, Fort Knox, Marquette, Appalaches',
    resource: 'metals',
    richness: 1,
    provinces: [
      'usa:Montana Sud-Ouest',
      'usa:Idaho Nord-Ouest',
      'usa:Alaska Est',
      'usa:Michigan Nord-Ouest',
      'usa:Kentucky',
    ],
    source: USGS,
  },
  {
    id: 'mx-silver',
    name: 'Zacatecas (argent), Cananea (cuivre)',
    resource: 'metals',
    richness: 3,
    provinces: ['mex:Zacatecas', 'mex:Sonora Nord-Ouest'],
    source: USGS,
  },
  {
    id: 'mx-misc',
    name: 'Sierra Madre (Chihuahua, Durango, San Luis Potosí)',
    resource: 'metals',
    richness: 2,
    provinces: [
      'mex:Sonora Sud-Est',
      'mex:Chihuahua Sud',
      'mex:Durango Sud',
      'mex:San Luis Potosí',
      'mex:Coahuila Nord',
    ],
    source: USGS,
  },
  {
    id: 'se-kiruna',
    name: 'Kiruna, Malmberget (fer)',
    resource: 'metals',
    richness: 3,
    circle: [20.5, 67.6, 250],
    nations: ['swe'],
    source: USGS,
  },
  {
    id: 'se-skelleftea',
    name: 'Skellefteå, Bergslagen',
    resource: 'metals',
    richness: 1,
    circle: [20.9, 64.75, 120],
    nations: ['swe'],
    source: USGS,
  },
  {
    id: 'fi-lapland',
    name: 'Kittilä (or), Terrafame (nickel)',
    resource: 'metals',
    richness: 1,
    circle: [27.0, 65.5, 300],
    nations: ['fin'],
    source: USGS,
  },
  {
    id: 'pl-lubin',
    name: 'KGHM Lubin (cuivre)',
    resource: 'metals',
    richness: 2,
    circle: [16.2, 51.4, 60],
    nations: ['pol'],
    source: USGS,
  },
  {
    id: 'pl-silesia',
    name: 'Charbon de Haute-Silésie',
    resource: 'metals',
    richness: 2,
    circle: [19.0, 50.25, 60],
    nations: ['pol'],
    source: USGS,
  },
  {
    id: 'ua-kryvyi-rih',
    name: 'Kryvyï Rih (fer)',
    resource: 'metals',
    richness: 3,
    provinces: ['ukr:Dnipropetrovsk'],
    source: USGS,
  },
  {
    id: 'ua-donbas',
    name: 'Donbass (charbon)',
    resource: 'metals',
    richness: 2,
    provinces: ['ukr:Donetsk', 'ukr:Lougansk'],
    source: USGS,
  },
  {
    id: 'ir-sarcheshmeh',
    name: 'Sarcheshmeh (cuivre), Tchador Malou (fer)',
    resource: 'metals',
    richness: 2,
    provinces: ['irn:Kerman Nord-Ouest', 'irn:Yazd Sud-Ouest'],
    source: USGS,
  },
  {
    id: 'pk-reko-diq',
    name: 'Reko Diq, Saindak',
    resource: 'metals',
    richness: 1,
    circle: [62.0, 29.1, 180],
    nations: ['pak'],
    source: USGS,
  },
  {
    id: 'pg-highlands',
    name: 'Ok Tedi, Porgera',
    resource: 'metals',
    richness: 2,
    circle: [142.5, -5.6, 250],
    nations: ['png'],
    source: USGS,
  },
  {
    id: 'id-grasberg',
    name: 'Grasberg (cuivre, or)',
    resource: 'metals',
    richness: 3,
    circle: [137.1, -4.05, 200],
    nations: ['idn'],
    source: USGS,
  },
  {
    id: 'id-nickel',
    name: 'Nickel de Sulawesi et Halmahera, étain de Bangka',
    resource: 'metals',
    richness: 2,
    provinces: [
      'idn:Sulawesi du Sud-Est',
      'idn:Sulawesi central',
      'idn:Moluques du Nord',
      'idn:Îles Bangka Belitung',
    ],
    source: USGS,
  },
  {
    id: 'nc-nickel',
    name: 'Nickel de Nouvelle-Calédonie',
    resource: 'metals',
    richness: 3,
    provinces: ['fra:Nouvelle-Calédonie (Sud)', 'fra:Nouvelle-Calédonie (Nord)'],
    source: USGS,
  },
  {
    id: 'ph-surigao',
    name: 'Surigao (nickel)',
    resource: 'metals',
    richness: 1,
    circle: [125.6, 9.6, 150],
    nations: ['phl'],
    source: USGS,
  },
  {
    id: 'cu-moa',
    name: 'Moa (nickel)',
    resource: 'metals',
    richness: 1,
    circle: [-74.9, 20.6, 100],
    nations: ['cub'],
    source: USGS,
  },
  {
    id: 'jm-bauxite',
    name: 'Bauxite jamaïcaine',
    resource: 'metals',
    richness: 1,
    circle: [-77.4, 18.1, 70],
    nations: ['jam'],
    source: USGS,
  },
  {
    id: 'kp-musan',
    name: 'Musan (fer)',
    resource: 'metals',
    richness: 1,
    circle: [129.2, 42.2, 130],
    nations: ['prk'],
    source: USGS,
  },
  {
    id: 'vn-quang-ninh',
    name: 'Quang Ninh (charbon)',
    resource: 'metals',
    richness: 1,
    circle: [107.2, 21.0, 70],
    nations: ['vnm'],
    source: USGS,
  },
  {
    id: 'uz-muruntau',
    name: 'Mourountaou (or), Almalyk (cuivre)',
    resource: 'metals',
    richness: 2,
    circle: [64.5, 41.5, 160],
    nations: ['uzb'],
    source: USGS,
  },
  {
    id: 'kg-kumtor',
    name: 'Koumtor (or)',
    resource: 'metals',
    richness: 1,
    circle: [78.2, 41.9, 150],
    nations: ['kgz'],
    source: USGS,
  },
  {
    id: 'am-kajaran',
    name: 'Kadjaran (cuivre, molybdène)',
    resource: 'metals',
    richness: 1,
    circle: [46.2, 39.15, 60],
    nations: ['arm'],
    source: USGS,
  },
  {
    id: 'ge-chiatura',
    name: 'Tchiatoura (manganèse)',
    resource: 'metals',
    richness: 1,
    circle: [43.3, 42.3, 60],
    nations: ['geo'],
    source: USGS,
  },
  {
    id: 'rs-bor',
    name: 'Bor (cuivre)',
    resource: 'metals',
    richness: 1,
    circle: [22.1, 44.1, 70],
    nations: ['srb'],
    source: USGS,
  },
  {
    id: 'es-riotinto',
    name: 'Ceinture pyriteuse ibérique',
    resource: 'metals',
    richness: 1,
    circle: [-7.2, 37.7, 90],
    nations: ['esp', 'prt'],
    source: USGS,
  },
  {
    id: 'ar-andes',
    name: 'Bajo de la Alumbrera, Veladero, lithium de la Puna',
    resource: 'metals',
    richness: 1,
    provinces: ['arg:Catamarca', 'arg:Jujuy', 'arg:San Juan'],
    source: USGS,
  },
  {
    id: 'sa-phosphate',
    name: 'Wa’ad Al Shamal (phosphates)',
    resource: 'metals',
    richness: 1,
    provinces: ['sau:Hudud ach-Chamaliya'],
    source: USGS,
  },

  // ————————————————————————————— Greniers agricoles —————————————————————————————
  {
    id: 'fr-beauce',
    name: 'Beauce et Brie',
    resource: 'food',
    richness: 3,
    provinces: ['fra:Seine-et-Marne'],
    source: FAO,
  },
  {
    id: 'fr-north',
    name: 'Plaines du Nord, Champagne, Normandie',
    resource: 'food',
    richness: 2,
    provinces: [
      'fra:Hauts-de-France',
      'fra:Grand Est',
      'fra:Normandie',
      'fra:Bretagne',
      'fra:Pays de la Loire',
      'fra:Bourgogne-Franche-Comté',
      'fra:Dordogne',
    ],
    source: FAO,
  },
  {
    id: 'fr-misc',
    name: 'Aquitaine, Massif central',
    resource: 'food',
    richness: 1,
    provinces: ['fra:Gironde', 'fra:Puy-de-Dôme', 'fra:Haute-Vienne'],
    source: FAO,
  },
  {
    id: 'ua-chernozem',
    name: 'Tchernoziom ukrainien',
    resource: 'food',
    richness: 3,
    provinces: ['ukr:Poltava', 'ukr:Vinnytsia', 'ukr:Tcherkassy', 'ukr:Kherson', 'ukr:Mykolaiv'],
    source: FAO,
  },
  {
    id: 'ua-steppe',
    name: 'Steppes et forêts-steppes ukrainiennes',
    resource: 'food',
    richness: 2,
    provinces: [
      'ukr:Odessa',
      'ukr:Kharkiv',
      'ukr:Khmelnitski',
      'ukr:Soumy',
      'ukr:Tchernihiv',
      'ukr:Zaporijjia',
      'ukr:Dnipropetrovsk',
      'ukr:Kiev',
      'ukr:Jytomyr',
      'ukr:Rivne',
      'ukr:Lviv',
      'ukr:Ivano-Frankivsk',
    ],
    source: FAO,
  },
  {
    id: 'ru-south',
    name: 'Kouban et Caucase du Nord',
    resource: 'food',
    richness: 3,
    provinces: ['rus:Krasnodar', 'rus:Stavropol', 'rus:Rostov'],
    source: FAO,
  },
  {
    id: 'ru-chernozem',
    name: 'Terres noires centrales et Volga',
    resource: 'food',
    richness: 2,
    provinces: [
      'rus:Voronej',
      'rus:Belgorod',
      'rus:Koursk',
      'rus:Tambov',
      'rus:Lipetsk',
      'rus:Orel',
      'rus:Saratov',
      'rus:Volgograd',
      "rus:République de l'Altaï Ouest",
    ],
    source: FAO,
  },
  {
    id: 'ru-misc-food',
    name: 'Céréales de l’Oural et de Sibérie du Sud, soja de l’Amour',
    resource: 'food',
    richness: 1,
    provinces: [
      'rus:Penza',
      'rus:Omsk Sud',
      'rus:Kourgan',
      'rus:Bachkirie Sud',
      'rus:Novossibirsk Ouest',
      'rus:Amour Sud',
      'rus:Tatarstan',
      'rus:Samara',
      'rus:Orenbourg Ouest',
    ],
    source: FAO,
  },
  {
    id: 'kz-wheat',
    name: 'Blé du Nord-Kazakhstan',
    resource: 'food',
    richness: 3,
    provinces: ['kaz:Kazakhstan-Septentrional', 'kaz:Kostanaï Nord'],
    source: FAO,
  },
  {
    id: 'kz-aqmola',
    name: 'Aqmola',
    resource: 'food',
    richness: 2,
    provinces: ['kaz:Aqmola Est', 'kaz:Aqmola Ouest'],
    source: FAO,
  },
  {
    id: 'us-corn-belt',
    name: 'Corn Belt',
    resource: 'food',
    richness: 3,
    provinces: [
      'usa:Iowa Ouest',
      'usa:Iowa Est',
      'usa:Illinois Sud',
      'usa:Nebraska Est',
      'usa:Kansas Est',
      'usa:Californie Sud',
    ],
    source: FAO,
  },
  {
    id: 'us-plains',
    name: 'Grandes Plaines et Midwest',
    resource: 'food',
    richness: 2,
    provinces: [
      'usa:Indiana',
      'usa:Nebraska Ouest',
      'usa:Kansas Ouest',
      'usa:Minnesota Sud',
      'usa:Dakota du Sud Est',
      'usa:Dakota du Nord Est',
      'usa:Missouri Nord-Ouest',
      'usa:Washington Est',
      'usa:Wisconsin Nord-Ouest',
      'usa:Idaho Sud-Est',
      'usa:Texas Nord-Ouest',
    ],
    source: FAO,
  },
  {
    id: 'us-misc-food',
    name: 'Delta du Mississippi, Sud-Est',
    resource: 'food',
    richness: 1,
    provinces: [
      'usa:Arkansas Nord-Est',
      'usa:Mississippi Nord',
      'usa:Géorgie Sud-Est',
      'usa:Ohio Sud-Ouest',
      'usa:Oklahoma Ouest',
      'usa:Dakota du Nord Ouest',
      'usa:Montana Est',
      'usa:Californie Nord',
    ],
    source: FAO,
  },
  {
    id: 'ca-prairies',
    name: 'Prairies canadiennes',
    resource: 'food',
    richness: 3,
    provinces: ['can:Saskatchewan Sud'],
    source: FAO,
  },
  {
    id: 'ca-prairies-2',
    name: 'Prairies (Manitoba, Alberta, Saskatchewan centre)',
    resource: 'food',
    richness: 2,
    provinces: ['can:Saskatchewan Centre', 'can:Manitoba Sud', 'can:Alberta Sud'],
    source: FAO,
  },
  {
    id: 'ar-pampa',
    name: 'Pampa humide',
    resource: 'food',
    richness: 3,
    provinces: ['arg:Buenos Aires Sud-Ouest', 'arg:Córdoba Sud', 'arg:Santa Fe Sud'],
    source: FAO,
  },
  {
    id: 'ar-pampa-2',
    name: 'Pampa et Mésopotamie argentine',
    resource: 'food',
    richness: 2,
    provinces: [
      'arg:Buenos Aires Nord-Est',
      'arg:Córdoba Nord',
      'arg:Santa Fe Nord',
      'arg:Entre Ríos',
      'arg:La Pampa Est',
    ],
    source: FAO,
  },
  {
    id: 'ar-misc',
    name: 'Sucre de Tucumán, vignes de Mendoza, Chaco',
    resource: 'food',
    richness: 1,
    provinces: ['arg:Tucumán', 'arg:Mendoza Nord', 'arg:Chaco'],
    source: FAO,
  },
  {
    id: 'br-soy',
    name: 'Soja du Mato Grosso et du Paraná, canne de São Paulo',
    resource: 'food',
    richness: 3,
    provinces: [
      'bra:Mato Grosso Nord-Est',
      'bra:Mato Grosso Sud-Est',
      'bra:Paraná Ouest',
      'bra:São Paulo Nord',
    ],
    source: FAO,
  },
  {
    id: 'br-cerrado',
    name: 'Cerrado et Sud du Brésil',
    resource: 'food',
    richness: 2,
    provinces: [
      'bra:Mato Grosso Sud-Ouest',
      'bra:Mato Grosso Nord-Ouest',
      'bra:Rio Grande do Sul Ouest',
      'bra:Goiás Sud-Ouest',
      'bra:Mato Grosso do Sul Sud',
      'bra:Mato Grosso do Sul Est',
      'bra:São Paulo Ouest',
      'bra:Minas Gerais Ouest',
      'bra:Bahia Ouest',
    ],
    source: FAO,
  },
  {
    id: 'br-misc-food',
    name: 'Matopiba, Santa Catarina',
    resource: 'food',
    richness: 1,
    provinces: [
      'bra:Santa Catarina',
      'bra:Tocantins Sud',
      'bra:Maranhão Sud',
      'bra:Piauí Sud-Ouest',
      'bra:Rio Grande do Sul Sud',
    ],
    source: FAO,
  },
  {
    id: 'in-punjab',
    name: 'Pendjab et Haryana',
    resource: 'food',
    richness: 3,
    provinces: [
      'ind:Pendjab Nord',
      'ind:Pendjab Sud',
      'ind:Haryana Nord',
      'ind:Uttar Pradesh Nord-Ouest',
    ],
    source: FAO,
  },
  {
    id: 'in-gangetic',
    name: 'Plaine du Gange, deltas',
    resource: 'food',
    richness: 2,
    provinces: [
      'ind:Haryana Sud',
      'ind:Uttar Pradesh Ouest',
      'ind:Uttar Pradesh Nord',
      'ind:Uttar Pradesh Est',
      'ind:Bihar Ouest',
      'ind:Bihar Est',
      'ind:Bengale-Occidental Sud',
      'ind:Bengale-Occidental Nord',
      'ind:Madhya Pradesh Ouest',
      'ind:Madhya Pradesh Est',
      'ind:Andhra Pradesh Nord-Est',
    ],
    source: FAO,
  },
  {
    id: 'in-misc-food',
    name: 'Coton du Deccan, delta de la Kaveri, thé d’Assam',
    resource: 'food',
    richness: 1,
    provinces: [
      'ind:Telangana Est',
      'ind:Maharashtra Nord-Est',
      'ind:Tamil Nadu Sud-Est',
      'ind:Karnataka Nord',
      'ind:Assam Sud-Ouest',
      'ind:Odisha Sud-Ouest',
    ],
    source: FAO,
  },
  {
    id: 'pk-punjab',
    name: 'Pendjab pakistanais',
    resource: 'food',
    richness: 3,
    circle: [72.8, 31.0, 220],
    nations: ['pak'],
    source: FAO,
  },
  {
    id: 'pk-sindh',
    name: 'Vallée de l’Indus (Sind)',
    resource: 'food',
    richness: 2,
    circle: [68.5, 26.5, 200],
    nations: ['pak'],
    source: FAO,
  },
  {
    id: 'cn-northeast',
    name: 'Plaine du Nord-Est (Sanjiang, Songliao)',
    resource: 'food',
    richness: 3,
    provinces: ['chn:Heilongjiang Est', 'chn:Jilin Nord-Ouest'],
    source: FAO,
  },
  {
    id: 'cn-north-plain',
    name: 'Plaine de Chine du Nord',
    resource: 'food',
    richness: 3,
    provinces: ['chn:Henan Est', 'chn:Shandong Ouest', 'chn:Anhui Nord'],
    source: FAO,
  },
  {
    id: 'cn-plains',
    name: 'Plaines du Yangzi et du Nord',
    resource: 'food',
    richness: 2,
    provinces: [
      'chn:Heilongjiang Sud',
      'chn:Henan Sud',
      'chn:Henan Nord',
      'chn:Shandong Sud-Ouest',
      'chn:Hebei Sud',
      'chn:Jiangsu Nord',
      'chn:Jiangsu Nord-Ouest',
      'chn:Hubei Est',
      'chn:Hunan Nord-Ouest',
      'chn:Jiangxi Nord-Ouest',
      'chn:Sichuan Est',
      'chn:Guangxi Sud',
    ],
    source: FAO,
  },
  {
    id: 'cn-misc-food',
    name: 'Liaoning, Chifeng, Ningxia',
    resource: 'food',
    richness: 1,
    provinces: [
      'chn:Liaoning Nord',
      'chn:Mongolie-Intérieure Est',
      'chn:Níngxià',
      'chn:Henan Ouest',
      'chn:Hunan Sud-Est',
    ],
    source: FAO,
  },
  {
    id: 'de-plains',
    name: 'Plaine germanique du Nord',
    resource: 'food',
    richness: 2,
    provinces: [
      'deu:Basse-Saxe',
      'deu:Mecklembourg-Poméranie-Occidentale',
      'deu:Schleswig-Holstein',
      'deu:Saxe-Anhalt',
      'deu:Brandebourg',
    ],
    source: FAO,
  },
  {
    id: 'pl-plains',
    name: 'Grande-Pologne, Lublin',
    resource: 'food',
    richness: 2,
    circle: [19.5, 52.0, 230],
    nations: ['pol'],
    source: FAO,
  },
  {
    id: 'hu-alfold',
    name: 'Grande Plaine hongroise',
    resource: 'food',
    richness: 2,
    circle: [20.2, 46.8, 150],
    nations: ['hun'],
    source: FAO,
  },
  {
    id: 'ro-baragan',
    name: 'Bărăgan, plaine valaque',
    resource: 'food',
    richness: 2,
    circle: [26.5, 44.3, 180],
    nations: ['rou'],
    source: FAO,
  },
  {
    id: 'bg-dobrudja',
    name: 'Dobroudja, plaine danubienne',
    resource: 'food',
    richness: 2,
    circle: [26.5, 43.6, 150],
    nations: ['bgr'],
    source: FAO,
  },
  {
    id: 'rs-vojvodina',
    name: 'Voïvodine',
    resource: 'food',
    richness: 2,
    circle: [20.0, 45.4, 110],
    nations: ['srb'],
    source: FAO,
  },
  {
    id: 'es-meseta',
    name: 'Castille-et-León, Andalousie',
    resource: 'food',
    richness: 2,
    circle: [-4.6, 40.0, 330],
    nations: ['esp'],
    source: FAO,
  },
  {
    id: 'it-padana',
    name: 'Plaine du Pô (Émilie)',
    resource: 'food',
    richness: 3,
    circle: [11.2, 44.8, 90],
    nations: ['ita'],
    source: FAO,
  },
  {
    id: 'it-puglia',
    name: 'Pouilles',
    resource: 'food',
    richness: 2,
    circle: [16.5, 41.0, 130],
    nations: ['ita'],
    source: FAO,
  },
  {
    id: 'gb-east',
    name: 'Est de l’Angleterre',
    resource: 'food',
    richness: 2,
    provinces: ['gbr:Midlands de l’Est', 'gbr:Southend-on-Sea'],
    source: FAO,
  },
  {
    id: 'dk-jutland',
    name: 'Jutland',
    resource: 'food',
    richness: 2,
    circle: [9.2, 56.2, 140],
    nations: ['dnk'],
    source: FAO,
  },
  {
    id: 'nl-dairy',
    name: 'Frise (élevage laitier)',
    resource: 'food',
    richness: 2,
    provinces: ['nld:Frise', 'nld:Gueldre', 'nld:Overijssel'],
    source: FAO,
  },
  {
    id: 'ie-pasture',
    name: 'Herbages irlandais',
    resource: 'food',
    richness: 2,
    circle: [-8.3, 53.0, 220],
    nations: ['irl'],
    source: FAO,
  },
  {
    id: 'eg-nile',
    name: 'Delta et vallée du Nil',
    resource: 'food',
    richness: 3,
    circle: [31.2, 30.6, 140],
    nations: ['egy'],
    source: FAO,
  },
  {
    id: 'eg-upper-nile',
    name: 'Haute-Égypte (vallée du Nil)',
    resource: 'food',
    richness: 1,
    circle: [31.8, 26.5, 220],
    nations: ['egy'],
    source: FAO,
  },
  {
    id: 'sd-gezira',
    name: 'Gezira',
    resource: 'food',
    richness: 2,
    circle: [33.4, 14.4, 150],
    nations: ['sdn'],
    source: FAO,
  },
  {
    id: 'et-highlands',
    name: 'Hauts plateaux éthiopiens',
    resource: 'food',
    richness: 1,
    circle: [38.5, 8.5, 300],
    nations: ['eth'],
    source: FAO,
  },
  {
    id: 'ng-north',
    name: 'Céréales du Nord nigérian, Middle Belt',
    resource: 'food',
    richness: 2,
    provinces: ['nga:Kano', 'nga:Kaduna', 'nga:Benue', 'nga:Katsina', 'nga:Niger'],
    source: FAO,
  },
  {
    id: 'ci-cocoa',
    name: 'Ceinture du cacao ivoirienne',
    resource: 'food',
    richness: 2,
    circle: [-5.8, 6.5, 220],
    nations: ['civ'],
    source: FAO,
  },
  {
    id: 'gh-cocoa',
    name: 'Cacao ghanéen',
    resource: 'food',
    richness: 2,
    circle: [-2.4, 7.0, 150],
    nations: ['gha'],
    source: FAO,
  },
  {
    id: 'ke-rift',
    name: 'Hautes terres du Kenya',
    resource: 'food',
    richness: 2,
    circle: [35.5, 0.3, 150],
    nations: ['ken'],
    source: FAO,
  },
  {
    id: 'za-maize',
    name: 'Triangle du maïs (État libre)',
    resource: 'food',
    richness: 2,
    provinces: ['zaf:État libre Sud-Ouest', 'zaf:KwaZulu-Natal Nord-Est'],
    source: FAO,
  },
  {
    id: 'ma-gharb',
    name: 'Gharb, Saïss, Souss',
    resource: 'food',
    richness: 2,
    circle: [-6.2, 33.8, 160],
    nations: ['mar'],
    source: FAO,
  },
  {
    id: 'dz-tell',
    name: 'Mitidja et hautes plaines céréalières',
    resource: 'food',
    richness: 2,
    provinces: ['dza:Blida', 'dza:Sétif', 'dza:Tiaret', 'dza:Médéa'],
    source: FAO,
  },
  {
    id: 'dz-tell-2',
    name: 'Tell oranais et constantinois, palmeraies',
    resource: 'food',
    richness: 1,
    provinces: [
      'dza:Mostaganem',
      'dza:Chlef',
      'dza:Sidi Bel Abbès',
      'dza:Tlemcen',
      'dza:Biskra',
      'dza:Batna',
      'dza:Oum El Bouaghi',
      'dza:Souk Ahras',
      'dza:Tizi Ouzou',
      'dza:Béjaïa',
      'dza:Djelfa',
      'dza:Skikda',
    ],
    source: FAO,
  },
  {
    id: 'tn-sahel',
    name: 'Sahel tunisien, cap Bon',
    resource: 'food',
    richness: 1,
    circle: [10.4, 35.6, 120],
    nations: ['tun'],
    source: FAO,
  },
  {
    id: 'th-central',
    name: 'Plaine centrale thaïlandaise',
    resource: 'food',
    richness: 3,
    circle: [100.3, 15.2, 180],
    nations: ['tha'],
    source: FAO,
  },
  {
    id: 'th-isan',
    name: 'Isan',
    resource: 'food',
    richness: 2,
    circle: [103.2, 15.8, 250],
    nations: ['tha'],
    source: FAO,
  },
  {
    id: 'vn-mekong',
    name: 'Delta du Mékong',
    resource: 'food',
    richness: 3,
    circle: [105.6, 10.0, 130],
    nations: ['vnm'],
    source: FAO,
  },
  {
    id: 'vn-red-river',
    name: 'Delta du fleuve Rouge',
    resource: 'food',
    richness: 2,
    circle: [106.2, 20.5, 80],
    nations: ['vnm'],
    source: FAO,
  },
  {
    id: 'mm-irrawaddy',
    name: 'Delta de l’Irrawaddy',
    resource: 'food',
    richness: 2,
    circle: [95.3, 17.0, 180],
    nations: ['mmr'],
    source: FAO,
  },
  {
    id: 'kh-tonle-sap',
    name: 'Tonlé Sap',
    resource: 'food',
    richness: 2,
    circle: [104.0, 12.8, 160],
    nations: ['khm'],
    source: FAO,
  },
  {
    id: 'bd-delta',
    name: 'Delta du Gange-Brahmapoutre',
    resource: 'food',
    richness: 2,
    circle: [90.0, 24.0, 260],
    nations: ['bgd'],
    source: FAO,
  },
  {
    id: 'id-java',
    name: 'Rizières de Java, Sulawesi du Sud',
    resource: 'food',
    richness: 2,
    provinces: [
      'idn:Java central',
      'idn:Java oriental Est',
      'idn:Sulawesi du Sud',
      'idn:Sumatra du Nord Nord',
    ],
    source: FAO,
  },
  {
    id: 'ph-luzon',
    name: 'Plaine centrale de Luçon',
    resource: 'food',
    richness: 2,
    circle: [120.7, 15.5, 100],
    nations: ['phl'],
    source: FAO,
  },
  {
    id: 'jp-rice',
    name: 'Hokkaidō, rizières de Niigata',
    resource: 'food',
    richness: 2,
    provinces: ['jpn:Hokkaidō Nord-Est', 'jpn:Niigata', 'jpn:Akita'],
    source: FAO,
  },
  {
    id: 'kr-jeolla',
    name: 'Plaines du Jeolla',
    resource: 'food',
    richness: 2,
    provinces: ['kor:Jeolla du Sud', 'kor:Jeolla du Nord'],
    source: FAO,
  },
  {
    id: 'sy-jazira',
    name: 'Djézireh (blé)',
    resource: 'food',
    richness: 2,
    circle: [41.0, 36.6, 160],
    nations: ['syr'],
    source: FAO,
  },
  {
    id: 'iq-mesopotamia',
    name: 'Mésopotamie (Babil, Qadisiyya)',
    resource: 'food',
    richness: 1,
    provinces: ['irq:Babil', 'irq:Al-Qadisiyya', 'irq:Wasit', 'irq:Diyala'],
    source: FAO,
  },
  {
    id: 'ir-caspian',
    name: 'Rives de la Caspienne',
    resource: 'food',
    richness: 1,
    provinces: ['irn:Golestan', 'irn:Mazandéran', 'irn:Guilan'],
    source: FAO,
  },
  {
    id: 'tr-anatolia',
    name: 'Plaine de Konya, Çukurova, GAP',
    resource: 'food',
    richness: 2,
    circle: [33.5, 37.8, 200],
    nations: ['tur'],
    source: FAO,
  },
  {
    id: 'au-wheat',
    name: 'Ceinture du blé australienne',
    resource: 'food',
    richness: 2,
    provinces: [
      'aus:Nouvelle-Galles du Sud Nord',
      'aus:Victoria Ouest',
      'aus:Australie-Occidentale Sud-Ouest',
    ],
    source: FAO,
  },
  {
    id: 'au-misc-food',
    name: 'Darling Downs, élevage du Queensland',
    resource: 'food',
    richness: 1,
    provinces: ['aus:Queensland Sud', 'aus:Queensland Sud-Ouest'],
    source: FAO,
  },
  {
    id: 'nz-farming',
    name: 'Canterbury, Waikato',
    resource: 'food',
    richness: 2,
    circle: [173.5, -40.5, 450],
    nations: ['nzl'],
    source: FAO,
  },
  {
    id: 'mx-farming',
    name: 'Sinaloa, Bajío, Michoacán',
    resource: 'food',
    richness: 2,
    provinces: ['mex:Sinaloa', 'mex:Guanajuato', 'mex:Michoacán'],
    source: FAO,
  },
  {
    id: 'co-coffee',
    name: 'Axe du café',
    resource: 'food',
    richness: 1,
    circle: [-75.6, 5.0, 130],
    nations: ['col'],
    source: FAO,
  },
  {
    id: 'uy-pampa',
    name: 'Pampa uruguayenne',
    resource: 'food',
    richness: 2,
    circle: [-56.0, -32.8, 260],
    nations: ['ury'],
    source: FAO,
  },
  {
    id: 'py-chaco',
    name: 'Soja du Paraguay oriental',
    resource: 'food',
    richness: 2,
    circle: [-55.8, -25.5, 250],
    nations: ['pry'],
    source: FAO,
  },

  // ————————————————————————————— Pôles électroniques et industriels —————————————————————————————
  {
    id: 'cn-pearl-river',
    name: 'Delta de la rivière des Perles (Shenzhen, Dongguan)',
    resource: 'electronics',
    richness: 3,
    provinces: ['chn:Hong Kong (Yuen Long)', 'chn:Guangdong Est'],
    source: SEMI,
  },
  {
    id: 'cn-yangtze',
    name: 'Delta du Yangzi (Shanghai, Suzhou, Wuxi)',
    resource: 'electronics',
    richness: 3,
    provinces: ['chn:Shanghai', 'chn:Jiangsu Sud-Est'],
    source: SEMI,
  },
  {
    id: 'cn-hubs',
    name: 'Canton, Nankin, Hangzhou, Chengdu, Chongqing, Wuhan, Zhengzhou',
    resource: 'electronics',
    richness: 2,
    provinces: [
      'chn:Guangdong Ouest',
      'chn:Jiangsu Sud',
      'chn:Zhejiang Nord-Est',
      'chn:Sichuan Sud-Est',
      'chn:Chongqing Sud-Ouest',
      'chn:Hubei Sud-Est',
      'chn:Henan Nord',
      'chn:Tianjin',
    ],
    source: SEMI,
  },
  {
    id: 'cn-misc-electronics',
    name: 'Qingdao, Xiamen, Xi’an, Shenyang, Zhuhai',
    resource: 'electronics',
    richness: 1,
    provinces: ['chn:Shandong Est', 'chn:Fujian Est', 'chn:Shaanxi Sud-Est', 'chn:Macao'],
    source: SEMI,
  },
  {
    id: 'tw-hsinchu',
    name: 'Parc scientifique de Hsinchu',
    resource: 'electronics',
    richness: 3,
    provinces: ['twn:Taoyuan'],
    source: SEMI,
  },
  {
    id: 'tw-misc',
    name: 'Taichung, Kaohsiung, Tainan',
    resource: 'electronics',
    richness: 2,
    provinces: ['twn:Changhua', 'twn:Kaohsiung', 'twn:Nouveau Taipei'],
    source: SEMI,
  },
  {
    id: 'kr-gyeonggi',
    name: 'Gyeonggi (Suwon, Hwaseong, Pyeongtaek)',
    resource: 'electronics',
    richness: 3,
    provinces: ['kor:Gyeonggi'],
    source: SEMI,
  },
  {
    id: 'kr-misc',
    name: 'Cheongju, Gumi, Changwon, Incheon',
    resource: 'electronics',
    richness: 2,
    provinces: [
      'kor:Chungcheong du Nord',
      'kor:Gyeongsang du Nord',
      'kor:Gyeongsang du Sud',
      'kor:Incheon',
      'kor:Daejeon',
    ],
    source: SEMI,
  },
  {
    id: 'jp-hubs',
    name: 'Kyūshū (« Silicon Island »), Chūkyō, Keihanshin, Kanagawa',
    resource: 'electronics',
    richness: 2,
    provinces: ['jpn:Kumamoto', 'jpn:Aichi', 'jpn:Osaka', 'jpn:Kanagawa'],
    source: SEMI,
  },
  {
    id: 'jp-misc',
    name: 'Fukuoka, Ōita, Hamamatsu, Nagano, Hiroshima, Sendai',
    resource: 'electronics',
    richness: 1,
    provinces: [
      'jpn:Fukuoka',
      'jpn:Miyazaki',
      'jpn:Shizuoka',
      'jpn:Hyōgo',
      'jpn:Nagano',
      'jpn:Hiroshima',
      'jpn:Miyagi',
      'jpn:Tochigi',
      'jpn:Yamaguchi',
    ],
    source: SEMI,
  },
  {
    id: 'us-silicon-valley',
    name: 'Silicon Valley',
    resource: 'electronics',
    richness: 3,
    provinces: ['usa:Californie Nord-Ouest'],
    source: SEMI,
  },
  {
    id: 'us-hubs',
    name: 'Seattle, Phoenix, Austin, Dallas, Boston, Hillsboro',
    resource: 'electronics',
    richness: 2,
    provinces: [
      'usa:Washington Ouest',
      'usa:Arizona Ouest',
      'usa:Texas Est',
      'usa:Massachusetts',
      'usa:Oregon Ouest',
    ],
    source: SEMI,
  },
  {
    id: 'us-misc-electronics',
    name: 'Research Triangle, Albuquerque, Boise, Détroit, Los Angeles',
    resource: 'electronics',
    richness: 1,
    provinces: [
      'usa:Caroline du Nord Est',
      'usa:Nouveau-Mexique Nord',
      'usa:Idaho Sud-Est',
      'usa:Michigan Sud-Est',
      'usa:Californie Sud-Est',
    ],
    source: SEMI,
  },
  {
    id: 'us-austin',
    name: 'Austin, San Antonio',
    resource: 'electronics',
    richness: 2,
    provinces: ['usa:Texas Sud'],
    source: SEMI,
  },
  {
    id: 'de-south',
    name: 'Bavière et Bade-Wurtemberg',
    resource: 'electronics',
    richness: 3,
    provinces: ['deu:Bavière Sud', 'deu:Bade-Wurtemberg'],
    source: SEMI,
  },
  {
    id: 'de-hubs',
    name: 'Silicon Saxony, Ruhr, Nuremberg',
    resource: 'electronics',
    richness: 2,
    provinces: ['deu:Saxe', 'deu:Rhénanie-du-Nord-Westphalie', 'deu:Bavière Nord'],
    source: SEMI,
  },
  {
    id: 'fr-grenoble',
    name: 'Grenoble-Crolles',
    resource: 'electronics',
    richness: 3,
    provinces: ['fra:Isère'],
    source: SEMI,
  },
  {
    id: 'fr-misc-electronics',
    name: 'Toulouse (aéronautique), Lyon, Rousset',
    resource: 'electronics',
    richness: 1,
    provinces: ['fra:Haute-Garonne', 'fra:Rhône', "fra:Provence-Alpes-Côte-d'Azur"],
    source: SEMI,
  },
  {
    id: 'gb-hubs',
    name: 'Vallée de la Tamise, Midlands, Bristol, Silicon Glen',
    resource: 'electronics',
    richness: 1,
    provinces: [
      'gbr:Oxfordshire',
      'gbr:Midlands de l’Ouest',
      'gbr:Sud-Ouest de l’Angleterre',
      'gbr:Sud-Ouest de l’Écosse',
      'gbr:Nord-Ouest de l’Angleterre',
    ],
    source: SEMI,
  },
  {
    id: 'nl-eindhoven',
    name: 'Eindhoven (Brainport)',
    resource: 'electronics',
    richness: 3,
    provinces: ['nld:Brabant-Septentrional'],
    source: SEMI,
  },
  {
    id: 'il-hubs',
    name: 'Silicon Wadi (Tel Aviv, Haïfa)',
    resource: 'electronics',
    richness: 2,
    provinces: ['isr:Tel Aviv', 'isr:Haïfa', 'isr:Centre'],
    source: SEMI,
  },
  {
    id: 'in-hubs',
    name: 'Bangalore, Hyderabad, Chennai',
    resource: 'electronics',
    richness: 2,
    provinces: ['ind:Karnataka Sud-Est', 'ind:Telangana Sud-Ouest', 'ind:Tamil Nadu Nord-Est'],
    source: SEMI,
  },
  {
    id: 'in-misc-electronics',
    name: 'Ahmedabad (Dholera)',
    resource: 'electronics',
    richness: 1,
    provinces: ['ind:Gujarat Est'],
    source: SEMI,
  },
  {
    id: 'sg-jurong',
    name: 'Jurong, Woodlands',
    resource: 'electronics',
    richness: 2,
    provinces: ['sgp:Sud-Ouest'],
    source: SEMI,
  },
  {
    id: 'my-penang',
    name: 'Penang, Kulim',
    resource: 'electronics',
    richness: 3,
    circle: [100.4, 5.4, 70],
    nations: ['mys'],
    source: SEMI,
  },
  {
    id: 'th-eastern',
    name: 'Ayutthaya, Eastern Seaboard',
    resource: 'electronics',
    richness: 2,
    circle: [100.9, 13.6, 110],
    nations: ['tha'],
    source: SEMI,
  },
  {
    id: 'vn-bac-ninh',
    name: 'Bac Ninh, Thai Nguyen',
    resource: 'electronics',
    richness: 2,
    circle: [106.0, 21.2, 70],
    nations: ['vnm'],
    source: SEMI,
  },
  {
    id: 'vn-saigon',
    name: 'Hô Chi Minh-Ville',
    resource: 'electronics',
    richness: 1,
    circle: [106.7, 10.8, 60],
    nations: ['vnm'],
    source: SEMI,
  },
  {
    id: 'ph-calabarzon',
    name: 'Calabarzon (Laguna, Cavite)',
    resource: 'electronics',
    richness: 1,
    circle: [121.1, 14.2, 60],
    nations: ['phl'],
    source: SEMI,
  },
  {
    id: 'mx-maquilas',
    name: 'Guadalajara, Tijuana, Ciudad Juárez, Monterrey',
    resource: 'electronics',
    richness: 2,
    provinces: ['mex:Jalisco', 'mex:Basse-Californie', 'mex:Chihuahua Nord', 'mex:Nuevo León'],
    source: SEMI,
  },
  {
    id: 'mx-misc-electronics',
    name: 'Querétaro (aéronautique)',
    resource: 'electronics',
    richness: 1,
    provinces: ['mex:Querétaro'],
    source: SEMI,
  },
  {
    id: 'br-hubs',
    name: 'São Paulo, zone franche de Manaus',
    resource: 'electronics',
    richness: 2,
    provinces: ['bra:São Paulo Est', 'bra:Amazonas Est'],
    source: SEMI,
  },
  {
    id: 'br-misc-electronics',
    name: 'Curitiba',
    resource: 'electronics',
    richness: 1,
    provinces: ['bra:Paraná Est'],
    source: SEMI,
  },
  {
    id: 'ru-hubs',
    name: 'Zelenograd, Saint-Pétersbourg',
    resource: 'electronics',
    richness: 2,
    provinces: ['rus:Moscou', 'rus:Saint-Pétersbourg'],
    source: SEMI,
  },
  {
    id: 'ru-misc-electronics',
    name: 'Nijni Novgorod, Novossibirsk, Iekaterinbourg',
    resource: 'electronics',
    richness: 1,
    provinces: ['rus:Nijni Novgorod', 'rus:Novossibirsk Est', 'rus:Sverdlovsk Sud'],
    source: SEMI,
  },
  {
    id: 'it-lombardy',
    name: 'Lombardie, Piémont',
    resource: 'electronics',
    richness: 2,
    circle: [8.6, 45.4, 90],
    nations: ['ita'],
    source: SEMI,
  },
  {
    id: 'es-catalonia',
    name: 'Catalogne, Pays basque',
    resource: 'electronics',
    richness: 1,
    circle: [2.1, 41.5, 60],
    nations: ['esp'],
    source: SEMI,
  },
  {
    id: 'cz-brno',
    name: 'Brno, Bohême industrielle',
    resource: 'electronics',
    richness: 1,
    circle: [16.6, 49.2, 70],
    nations: ['cze'],
    source: SEMI,
  },
  {
    id: 'pl-wroclaw',
    name: 'Wrocław',
    resource: 'electronics',
    richness: 1,
    circle: [17.0, 51.1, 50],
    nations: ['pol'],
    source: SEMI,
  },
  {
    id: 'ie-cork',
    name: 'Cork, Leixlip',
    resource: 'electronics',
    richness: 1,
    circle: [-8.5, 51.9, 70],
    nations: ['irl'],
    source: SEMI,
  },
  {
    id: 'se-gothenburg',
    name: 'Göteborg',
    resource: 'electronics',
    richness: 1,
    circle: [12.0, 57.7, 70],
    nations: ['swe'],
    source: SEMI,
  },
  {
    id: 'ch-zurich',
    name: 'Zurich',
    resource: 'electronics',
    richness: 1,
    circle: [8.5, 47.4, 50],
    nations: ['che'],
    source: SEMI,
  },
  {
    id: 'tr-kocaeli',
    name: 'Kocaeli, Bursa',
    resource: 'electronics',
    richness: 1,
    circle: [29.6, 40.5, 90],
    nations: ['tur'],
    source: SEMI,
  },
  // ——————————— Productions domestiques modestes (pays pauvres en ressources) ———————————
  // Petits gisements réels de pays réputés « sans » : production faible mais existante.
  {
    id: 'jp-niigata',
    name: 'Minami-Nagaoka, Niigata (gaz et pétrole)',
    resource: 'oil',
    richness: 1,
    provinces: ['jpn:Niigata'],
    source: EIA,
  },
  {
    id: 'jp-hishikari',
    name: 'Mine d’or de Hishikari (Kagoshima)',
    resource: 'metals',
    richness: 1,
    provinces: ['jpn:Kumamoto'],
    source: USGS,
  },
  {
    id: 'sa-qassim',
    name: 'Qassim (blé, dattes, cultures irriguées)',
    resource: 'food',
    richness: 1,
    provinces: ['sau:Qasim'],
    source: FAO,
  },
  {
    id: 'sa-jawf',
    name: 'Al-Jawf (céréales et oliviers irrigués)',
    resource: 'food',
    richness: 1,
    provinces: ['sau:Jawf'],
    source: FAO,
  },
  {
    id: 'de-mittelplate',
    name: 'Mittelplate (Mer des Wadden)',
    resource: 'oil',
    richness: 1,
    provinces: ['deu:Schleswig-Holstein'],
    source: EIA,
  },
  {
    id: 'de-lower-saxony',
    name: 'Gaz de Basse-Saxe',
    resource: 'oil',
    richness: 1,
    provinces: ['deu:Basse-Saxe'],
    source: EIA,
  },
  {
    id: 'nr-phosphate',
    name: 'Phosphates de Nauru',
    resource: 'metals',
    richness: 1,
    provinces: ['nru:Anibare'],
    source: USGS,
  },
  {
    id: 'mt-kirkop',
    name: 'Kirkop (semi-conducteurs)',
    resource: 'electronics',
    richness: 1,
    provinces: ['mlt:La Valette'],
    source: SEMI,
  },
];
