import type { WeaponSystemInput } from '@redline/shared';

/** Fiche vierge proposée à la création (à compléter ; volontairement invalide tant que l'id est vide). */
export function blankSystem(): WeaponSystemInput {
  return {
    id: '',
    name: '',
    doctrine: 'us',
    origin: 'US',
    category: 'fighter',
    roles: [],
    generation: 4,
    targetClass: 'aircraft',
    movement: 'air',
    canCapture: false,
    cost: { money: 1000, resources: { oil: 20, metals: 30, electronics: 40 } },
    buildTimeH: 24,
    upkeepPerDay: 20,
    speedKmh: 2000,
    operationalRadiusKm: 600,
    weaponRangeKm: { min: 1, max: 80 },
    damage: {
      infantry: 2,
      armor: 2,
      aircraft: 10,
      helicopter: 8,
      drone: 5,
      ship: 2,
      submarine: 0,
      missile: 1,
      building: 4,
    },
    hp: 25,
    armor: 0.1,
    stealth: 0,
    detectionRangeKm: 120,
    ew: { jamming: 0.1, jamResistance: 0.3 },
    payload: { slots: 6 },
    unitSize: 1,
    requires: [],
    licensable: false,
    exportable: true,
    icon: 'fighter',
    sheet: {
      engine: null,
      lengthM: null,
      wingspanM: null,
      mtowKg: null,
      warheadKg: null,
      speedLabel: null,
      rangeKm: null,
    },
    enabled: true,
  };
}
